[package]
name = "commx-web"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
commx-core.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
postcard.workspace = true
snow.workspace = true
hex.workspace = true
zeroize.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
commxd.workspace = true
tokio.workspace = true
