[package]
name = "commxd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
commx-core = { workspace = true, features = ["native"] }
anyhow.workspace = true
serde_json.workspace = true
rand.workspace = true
snow.workspace = true
tokio.workspace = true
clap.workspace = true
libc.workspace = true
hex.workspace = true
postcard.workspace = true
serde.workspace = true
blake3.workspace = true
sha1 = "0.10"
data-encoding.workspace = true
zeroize.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
commx-core.workspace = true
hex.workspace = true
serde_json.workspace = true
libc.workspace = true
